"use client";

import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  PDFDownloadLink,
} from "@react-pdf/renderer";
import { GeneratedLetter } from "@/lib/types";

const styles = StyleSheet.create({
  page: {
    padding: 60,
    fontSize: 11,
    fontFamily: "Helvetica",
    lineHeight: 1.5,
    color: "#1a1a1a",
  },
  header: {
    fontSize: 9,
    color: "#666",
    marginBottom: 20,
    textAlign: "right",
  },
  subject: {
    fontSize: 12,
    fontFamily: "Helvetica-Bold",
    marginBottom: 16,
  },
  body: {
    fontSize: 11,
    lineHeight: 1.6,
  },
  footer: {
    position: "absolute",
    bottom: 40,
    left: 60,
    right: 60,
    fontSize: 8,
    color: "#999",
    textAlign: "center",
  },
});

function LetterDocument({ letter }: { letter: GeneratedLetter }) {
  // Split body into lines, then chunk into pages
  const lines = letter.body.split("\n");
  const linesPerPage = 45;
  const pages: string[][] = [];

  for (let i = 0; i < lines.length; i += linesPerPage) {
    pages.push(lines.slice(i, i + linesPerPage));
  }

  return (
    <Document>
      {pages.map((pageLines, pageIdx) => (
        <Page key={pageIdx} size="LETTER" style={styles.page}>
          {pageIdx === 0 && (
            <>
              <Text style={styles.header}>
                Generated by LUXBIN Coinbase Recovery Tool | {letter.date}
              </Text>
              <Text style={styles.subject}>{letter.subject}</Text>
            </>
          )}
          <Text style={styles.body}>{pageLines.join("\n")}</Text>
          <Text style={styles.footer}>
            Page {pageIdx + 1} of {pages.length} | LUXBIN Coinbase Recovery Tool - Not Legal Advice
          </Text>
        </Page>
      ))}
    </Document>
  );
}

export default function LetterPDF({ letter }: { letter: GeneratedLetter }) {
  const filename = `LUXBIN_${letter.agency.toUpperCase()}_Complaint_${letter.date.replace(/[, ]+/g, "_")}.pdf`;

  return (
    <div className="px-4 py-3 border-b border-luxbin-border bg-luxbin-darker">
      <PDFDownloadLink
        document={<LetterDocument letter={letter} />}
        fileName={filename}
      >
        {({ loading }) => (
          <button className="px-4 py-2 text-sm rounded-lg bg-luxbin-gold text-luxbin-dark font-medium hover:bg-luxbin-gold-light transition-colors">
            {loading ? "Generating PDF..." : `Download ${filename}`}
          </button>
        )}
      </PDFDownloadLink>
    </div>
  );
}
